### PR TITLE
1.20 Iris 1.7 Support

### PR DESCRIPTION
**Pull request by voodoofrog**
This provides the correct sun/moon positions to Iris so that shaderpacks supporting Iris' sun and moon position uniforms will work correctly with Caelum.

### CODE REVIEW

**Comment by jmb05** [comment]
This looks like a nice addition, but I found an issue. When I tried it with the Complementary Shaderpack the sun and moon where at the correct location but the halo of the sun was wrong.

**Comment by voodoofrog** [comment]
Yes, as I stated it works for shaderpacks that support Iris' Sun/Moon uniforms. As far as I've seen, BSL or any of it's derivatives (which Complementary is) do not use this feature and instead hardcode the positions themselves.

**Comment by voodoofrog** [comment]
Photon is an example of a shaderpack which _does_ use the uniforms, although it does also move their angles a bit (I assume that's an aesthetic choice).

**Comment by voodoofrog** [comment]
Just added another Iris mixin to handle the new moon config setting. From my own testing, setting this to false looks much better with the shaderpack I use for testing so that's been handy.

**Comment by voodoofrog** [comment]
Just to illustrate better about all this, here's a screenshot of Photon, with the shaders own sun angle set back to 0, taken somewhere near the world border...

**Review by jmb05 — APPROVED** [review]

**Pull request merged**
